package com.banana.spytutors.web.service;

import java.util.ArrayList;
import java.util.List;

import org.apache.commons.lang3.StringUtils;
import org.springframework.stereotype.Component;

import com.banana.spytutors.web.dto.CountryDTO;
import com.banana.spytutors.web.dto.CurrencyDTO;
import com.banana.spytutors.web.dto.PriceRangePerHourDTO;
import com.banana.spytutors.web.dto.CampaignDTO;

/**
 * 
 * @author ANKEM
 *
 */

@Component
public class RefDataServiceImpl implements RefDataService {

	private static final long serialVersionUID = 7521889013387774496L;
	
	@Override
	public List<CurrencyDTO> fetchCurrencyList() {
		List<CurrencyDTO> currencyList = new ArrayList<CurrencyDTO>(0);		
		currencyList.add(new CurrencyDTO("INR", "â‚¹"));
		currencyList.add(new CurrencyDTO("ARS", "$"));
		currencyList.add(new CurrencyDTO("AUD", "$"));
		currencyList.add(new CurrencyDTO("BBD", "$"));
		currencyList.add(new CurrencyDTO("BRL", "R$"));
		currencyList.add(new CurrencyDTO("GBP", "Â£"));
		currencyList.add(new CurrencyDTO("CAD", "$"));
		currencyList.add(new CurrencyDTO("CLP", "$"));
		currencyList.add(new CurrencyDTO("CNY", "å…ƒ"));
		currencyList.add(new CurrencyDTO("CZK", "KÄ�"));
		currencyList.add(new CurrencyDTO("DKK", "kr"));
		currencyList.add(new CurrencyDTO("XCD", "$"));
		currencyList.add(new CurrencyDTO("EGP", "Â£"));
		currencyList.add(new CurrencyDTO("EEK", "kr"));
		currencyList.add(new CurrencyDTO("EUR", "â‚¬"));
		currencyList.add(new CurrencyDTO("HKD", "å…ƒ"));
		currencyList.add(new CurrencyDTO("HUF", "Ft"));
		currencyList.add(new CurrencyDTO("ISK", "kr"));
		currencyList.add(new CurrencyDTO("IDR", "Rp"));
		currencyList.add(new CurrencyDTO("ILS", "â‚ª"));
		currencyList.add(new CurrencyDTO("JMD", "J$"));
		currencyList.add(new CurrencyDTO("JPY", "Â¥"));
		currencyList.add(new CurrencyDTO("LVL", "Ls"));
		currencyList.add(new CurrencyDTO("LBP", "Â£"));
		currencyList.add(new CurrencyDTO("LTL", "Lt"));
		currencyList.add(new CurrencyDTO("MYR", "RM"));
		currencyList.add(new CurrencyDTO("MXN", "$"));
		currencyList.add(new CurrencyDTO("NAD", "$"));
		currencyList.add(new CurrencyDTO("NPR", "Rs"));
		currencyList.add(new CurrencyDTO("NZD", "$"));
		currencyList.add(new CurrencyDTO("NOK", "kr"));
		currencyList.add(new CurrencyDTO("OMR", "ï·¼"));
		currencyList.add(new CurrencyDTO("PKR", "Rs"));
		currencyList.add(new CurrencyDTO("PAB", "B/."));
		currencyList.add(new CurrencyDTO("PHP", "Ph"));
		currencyList.add(new CurrencyDTO("PLN", "zÅ‚"));
		currencyList.add(new CurrencyDTO("QAR", "ï·¼"));
		currencyList.add(new CurrencyDTO("RON", "le"));
		currencyList.add(new CurrencyDTO("RUB", "â‚½"));		
		currencyList.add(new CurrencyDTO("SAR", "ï·¼"));
		currencyList.add(new CurrencyDTO("SGD", "$"));
		currencyList.add(new CurrencyDTO("ZAR", "R"));
		currencyList.add(new CurrencyDTO("KRW", "â‚©"));
		currencyList.add(new CurrencyDTO("LKR", "Rs"));
		currencyList.add(new CurrencyDTO("SEK", "kr"));
		currencyList.add(new CurrencyDTO("CHF", "CHF"));
		currencyList.add(new CurrencyDTO("THB", "à¸¿"));
		currencyList.add(new CurrencyDTO("TRY", "YTL"));
		currencyList.add(new CurrencyDTO("USD", "$"));
		currencyList.add(new CurrencyDTO("VEF", "Bs"));
		currencyList.add(new CurrencyDTO("AED", "Ø¯Ø±Ù‡Ù… Ø¥Ù…Ø§Ø±Ø§ØªÙŠ"));
		currencyList.add(new CurrencyDTO("XOF", "CFA"));
		currencyList.add(new CurrencyDTO("BHD", "Ø¯ÙŠÙ†Ø§Ø± Ø¨Ø­Ø±ÙŠÙ†ÙŠ"));	
		currencyList.add(new CurrencyDTO("XAF", "FCFA"));
		currencyList.add(new CurrencyDTO("CYP", "Â£"));
		currencyList.add(new CurrencyDTO("JOD", "Ø¯ÙŠÙ†Ø§Ø± Ø£Ø±Ø¯Ù†ÙŠ"));
		currencyList.add(new CurrencyDTO("KES", "KSh"));
		currencyList.add(new CurrencyDTO("KES", "Ø¯Ø±Ù‡Ù… Ù…ØºØ±Ø¨ÙŠ"));
	
		
		return currencyList;
	}
	
	/**
	 * Need to fecth from the service - Once Springdata and mongo DB integration done fetch the list.The process of adding the mockup subject list will continue until
	 * the development team lost their energy !!!!!!!!!!!!!
	 */
	@Override
	public List<CampaignDTO> fecthSubjectList() {
		
		List<CampaignDTO> subjectList = new ArrayList<CampaignDTO>(0);
		subjectList.add(new CampaignDTO("Agriculture", "University", "none", "all"));
		subjectList.add(new CampaignDTO("Animal Husbandry","University","Sciences","all"));
		subjectList.add(new CampaignDTO("Anthropology","University","Sciences","all"));		
		subjectList.add(new CampaignDTO("Botany","University","Sciences","all"));
		subjectList.add(new CampaignDTO("Chemistry","University","Sciences","all"));
		subjectList.add(new CampaignDTO("Civil Engineering","University","Engineering","all"));
		subjectList.add(new CampaignDTO("Commerce and Accountancy","University","Arts","all"));
		subjectList.add(new CampaignDTO("Economics","University","Engineering","all"));
		subjectList.add(new CampaignDTO("Electrical Engineering","University","Sciences","all"));
		subjectList.add(new CampaignDTO("Geography","University","Arts","all"));
		subjectList.add(new CampaignDTO("Geology","University","Sciences","all"));
		subjectList.add(new CampaignDTO("History","University","Arts","all"));
		subjectList.add(new CampaignDTO("Law","University","Arts","all"));
		subjectList.add(new CampaignDTO("Management","University","Arts","all"));
		subjectList.add(new CampaignDTO("Mathematics","all","Sciences","all"));
		subjectList.add(new CampaignDTO("Mechanical Engineering","University","Engineering","all"));
		subjectList.add(new CampaignDTO("Medical Science","University","Medicine","all"));
		subjectList.add(new CampaignDTO("Philosophy","University","Arts","all"));
		subjectList.add(new CampaignDTO("Physics","University","Sciences","all"));
		subjectList.add(new CampaignDTO("Political Science","University","Arts","all"));
		subjectList.add(new CampaignDTO("Psychology","University","Arts","all"));
		subjectList.add(new CampaignDTO("Public Administration","University","Arts","all"));
		subjectList.add(new CampaignDTO("Sociology","University","Arts","all"));
		subjectList.add(new CampaignDTO("Statistics","University","Sciences","all"));
		subjectList.add(new CampaignDTO("Zoology","University","Sciences","all"));
		subjectList.add(new CampaignDTO("Veterinary Science","University","Sciences","all"));
		subjectList.add(new CampaignDTO("International Relations","University","Arts","all"));
		
		/**language list for india **/
		subjectList.add(new CampaignDTO("Assamese","University","Language","India"));
		subjectList.add(new CampaignDTO("Bengali ","University","Language","India"));
		subjectList.add(new CampaignDTO("Bodo","University","Language","India"));
		subjectList.add(new CampaignDTO("Dogri","University","Language","India"));
		subjectList.add(new CampaignDTO("Gujarati","University","Language","India"));
		subjectList.add(new CampaignDTO("Hindi","University","Language","India"));
		subjectList.add(new CampaignDTO("Kannada","University","Language","India"));
		subjectList.add(new CampaignDTO("Kashmiri","University","Language","India"));
		subjectList.add(new CampaignDTO("Konkani","University","Language","India"));
		subjectList.add(new CampaignDTO("Maithili","University","Language","India"));
		subjectList.add(new CampaignDTO("Malayalam","University","Language","India"));
		subjectList.add(new CampaignDTO("Manipuri","University","Language","India"));
		subjectList.add(new CampaignDTO("Marathi","University","Language","India"));
		subjectList.add(new CampaignDTO("Nepali","University","Language","India"));
		subjectList.add(new CampaignDTO("Oriya","University","Language","India"));
		subjectList.add(new CampaignDTO("Punjabi","University","Language","India"));
		subjectList.add(new CampaignDTO("Sanskrit","University","Language","India"));
		subjectList.add(new CampaignDTO("Santhali","University","Language","India"));
		subjectList.add(new CampaignDTO("Sindhi","University","Language","India"));
		subjectList.add(new CampaignDTO("Tamil","University","Language","India"));
		subjectList.add(new CampaignDTO("Telugu","University","Language","India"));
		subjectList.add(new CampaignDTO("Urdu ","University","Language","India"));
		subjectList.add(new CampaignDTO("English","University","Language","all"));		
		
		return subjectList;
	}

	@Override
	public List<PriceRangePerHourDTO> fetchPriceRangePerHourDTOList(
			CountryDTO country) {		
		List<CurrencyDTO> currencyList = fetchCurrencyList();
	    CurrencyDTO requiredCurrency = null;
	    for (CurrencyDTO currency : currencyList) {
			if(StringUtils.equalsIgnoreCase(country.getCurrencyCode(), currency.getCurrencyCode())){
				requiredCurrency = currency;
				break;
			}
		}
	    if(requiredCurrency == null){
	    	requiredCurrency = new CurrencyDTO(country.getCurrencyCode(), country.getCurrencyCode());	    			
	    }
		List<PriceRangePerHourDTO> priceRangePerHourList = new ArrayList<PriceRangePerHourDTO>(0);
		priceRangePerHourList.add(new PriceRangePerHourDTO("10", "40", requiredCurrency));
		priceRangePerHourList.add(new PriceRangePerHourDTO("40", "60", requiredCurrency));
		priceRangePerHourList.add(new PriceRangePerHourDTO("60", "80", requiredCurrency));
		priceRangePerHourList.add(new PriceRangePerHourDTO("80", "100", requiredCurrency));
		priceRangePerHourList.add(new PriceRangePerHourDTO("100", "120", requiredCurrency));
		priceRangePerHourList.add(new PriceRangePerHourDTO("120", "140", requiredCurrency));
		priceRangePerHourList.add(new PriceRangePerHourDTO("140", "160", requiredCurrency));
		priceRangePerHourList.add(new PriceRangePerHourDTO("160", "260", requiredCurrency));
		priceRangePerHourList.add(new PriceRangePerHourDTO("260", "460", requiredCurrency));
		priceRangePerHourList.add(new PriceRangePerHourDTO("460", "660", requiredCurrency));
		priceRangePerHourList.add(new PriceRangePerHourDTO("660", "860", requiredCurrency));
		priceRangePerHourList.add(new PriceRangePerHourDTO("860", "1000", requiredCurrency));
		priceRangePerHourList.add(new PriceRangePerHourDTO("", "1000", requiredCurrency));
		
		return priceRangePerHourList;
	}

	@Override
	public List<String> fetchQualificationList() {
		List<String> qualificationList = new ArrayList<String>(0);
		qualificationList.add("Bachelor of Fine Arts (B.F.A.)");
		qualificationList.add("Bachelor of Social Work (B.S.W.)");
		qualificationList.add("Bachelor of Engineering (B.Eng.)");
		qualificationList.add("Bachelor of Science in Public Affairs (B.S.P.A)");
		qualificationList.add("Bachelor of Science in Nursing (B.S.N.)");
		qualificationList.add("Bachelor of Philosophy (B.Phil.)");		
		qualificationList.add("Bachelor of Design (B.Des.)");
		qualificationList.add("Bachelor of Architecture (B.Arch.)");
		qualificationList.add("Bachelor of Biomedical Science");
		qualificationList.add("Bachelor of Business Administration");
		qualificationList.add("Bachelor of Clinical Science");
		qualificationList.add("Bachelor of Commerce");
		qualificationList.add("Bachelor of Computer Applications");
		qualificationList.add("Bachelor of Computer Information Systems");
		qualificationList.add("Bachelor of Science in Construction Technology");
		qualificationList.add("Bachelor of Criminal Justice");
		qualificationList.add("Bachelor of Divinity");
		qualificationList.add("Bachelor of Economics");
		qualificationList.add("Bachelor of Education");
		qualificationList.add("Bachelor of Information Systems");
		qualificationList.add("Bachelor of Management");
		qualificationList.add("Bachelor of Music");
		qualificationList.add("Bachelor of Pharmacy");
		qualificationList.add("Bachelor of Philosophy");
		qualificationList.add("Bachelor of Social Work");
		qualificationList.add("Bachelor of Technology");
		qualificationList.add("Bachelor of Accountancy");
		qualificationList.add("Bachelor of Arts in American Studies");
		qualificationList.add("Bachelor of Arts in American Indian Studies");
		qualificationList.add("Bachelor of Arts in Applied Psychology");
		qualificationList.add("Bachelor of Arts in Biology");
		qualificationList.add("Bachelor of Arts in Anthropology");
		qualificationList.add("Bachelor of Arts in Child Advocacy");
		qualificationList.add("Bachelor of Arts in Clinical Psychology");
		qualificationList.add("Bachelor of Arts in Forensic Psychology");
		qualificationList.add("Bachelor of Arts in Organizational Psychology");
		qualificationList.add("Bachelor of Science in Aerospace Engineering");
		qualificationList.add("Bachelor of Science in Actuarial");
		qualificationList.add("Bachelor of Science in Agriculture");
		qualificationList.add("Bachelor of Science in Architecture");
		qualificationList.add("Bachelor of Science in Architectural Engineering");
		qualificationList.add("Bachelor of Science in Biology");
		qualificationList.add("Bachelor of Science in Biomedical Engineering");
		qualificationList.add("Bachelor of Science in Business Administration");
		qualificationList.add("Bachelor of Science in Business and Technology");
		qualificationList.add("Bachelor of Science in Chemical Engineering");
		qualificationList.add("Bachelor of Science in Chemistry");
		qualificationList.add("Bachelor of Science in Civil Engineering");
		qualificationList.add("Bachelor of Science in Clinical Laboratory Science");
		qualificationList.add("Bachelor of Science in Cognitive Science");
		qualificationList.add("Bachelor of Science in Computer Engineering");
		qualificationList.add("Bachelor of Science in  Computer Science");
		qualificationList.add("Bachelor of Science in Construction Engineering");
		qualificationList.add("Bachelor of Science in Construction Management");
		qualificationList.add("Bachelor of Science in Criminal Justice");
		qualificationList.add("Bachelor of Science in Criminology");
		qualificationList.add("Bachelor of Science in Diagnostic Radiography");
		qualificationList.add("Bachelor of Science in Education");
		qualificationList.add("Bachelor of Science in Electrical Engineering");
		qualificationList.add("Bachelor of Science in Engineering Physics");
		qualificationList.add("Bachelor of Science in Engineering Science");
		qualificationList.add("Bachelor of Science in Engineering Technology");
		qualificationList.add("Bachelor of Science in English Literature");
		qualificationList.add("Bachelor of Science in Environmental Engineering");		
		qualificationList.add("Bachelor of Science in Environmental Science");
		qualificationList.add("Bachelor of Science in Environmental Studies");
		qualificationList.add("Bachelor of Science in Food Science");
		qualificationList.add("Bachelor of Science in Foreign Service");
		qualificationList.add("Bachelor of Science in Forensic Science");
		qualificationList.add("Bachelor of Science in Forestry");
		qualificationList.add("Bachelor of Science in History");
		qualificationList.add("Bachelor of Science in Hospitality Management");
		qualificationList.add("Bachelor of Science in Human Resources Management");
		qualificationList.add("Bachelor of Science in Industrial Engineering");
		qualificationList.add("Bachelor of Science in Information Technology");
		qualificationList.add("Bachelor of Science in Information Systems");
		qualificationList.add("Bachelor of Science in Integrated Science");
		qualificationList.add("Bachelor of Science in International Relations");
		qualificationList.add("Bachelor of Science in Journalism");
		qualificationList.add("Bachelor of Science in Legal Management");
		qualificationList.add("Bachelor of Science in Management");
		qualificationList.add("Bachelor of Science in Manufacturing Engineering");
		qualificationList.add("Bachelor of Science in Marketing");
		qualificationList.add("Bachelor of Science in Mathematics");
		qualificationList.add("Bachelor of Science in Mechanical Engineering");
		qualificationList.add("Bachelor of Science in Medical Technology");
		qualificationList.add("Bachelor of Science in Meteorology");
		qualificationList.add("Bachelor of Science in Microbiology");
		qualificationList.add("Bachelor of Science in Mining Engineering");
		qualificationList.add("Bachelor of Science in Molecular Biology");
		qualificationList.add("Bachelor of Science in Neuroscience");
		qualificationList.add("Bachelor of Science in Nursing");		
		qualificationList.add("Bachelor of Science in Nutrition science");
		qualificationList.add("Bachelor of Science in Software Engineering");
		qualificationList.add("Bachelor of Science in Petroleum Engineering");
		qualificationList.add("Bachelor of Science in Podiatry");
		qualificationList.add("Bachelor of Science in Pharmacology");
		qualificationList.add("Bachelor of Science in Pharmacy");
		qualificationList.add("Bachelor of Science in Physical Therapy");
		qualificationList.add("Bachelor of Science in Physics");
		qualificationList.add("Bachelor of Science in Plant Science");
		qualificationList.add("Bachelor of Science in Politics");
		qualificationList.add("Bachelor of Science in Psychology");
		qualificationList.add("Bachelor of Science in Public Safety");
		qualificationList.add("Bachelor of Science in Quantity Surveying Engineering");
		qualificationList.add("Bachelor of Science in Radiologic Technology");
		qualificationList.add("Bachelor of Science in Real-Time Interactive Simulation");
		qualificationList.add("Bachelor of Science in Religion");
		qualificationList.add("Bachelor of Science in Respiratory Therapy");
		qualificationList.add("Bachelor of Science in Risk Management and Insurance");
		qualificationList.add("Bachelor of Science in Sports Management");
		qualificationList.add("Bachelor of Science in Science Education");
		qualificationList.add("Bachelor of Science in Sports Management");
		qualificationList.add("Bachelor of Science in Systems Engineering");
		qualificationList.add("Bachelor of Science in Veterinary Technology");
		
		qualificationList.add("Bachelor of Music in Jazz Studies");
		qualificationList.add("Bachelor of Music in Composition");
		qualificationList.add("Bachelor of Music in Performance");
		qualificationList.add("Bachelor of Music in Theory");
		qualificationList.add("Bachelor of Music in Music Education");	
		
		qualificationList.add("Master of Accountancy");
		qualificationList.add("Master of Advanced Study");
		qualificationList.add("Master of Applied Finance");
		qualificationList.add("Master of Applied Mathematical Sciences");
		qualificationList.add("Master of Applied Science");
		qualificationList.add("Master of Architecture");
		qualificationList.add("Master of Arts");
		qualificationList.add("Master of Arts in Liberal Studies");
		qualificationList.add("Master of Arts in Strategic Communication Management");
		qualificationList.add("Master of Arts in Teaching");
		qualificationList.add("Master of Bioinformatics");
		qualificationList.add("Master of Business Administration");
		qualificationList.add("Master of Business Administration Management of Technology");
		qualificationList.add("Master of Business");
		qualificationList.add("Master of Business Economics");
		qualificationList.add("Master of Business Engineering");
		qualificationList.add("Master of Business Informatics");
		qualificationList.add("Master of Chemistry");
		qualificationList.add("Master of City Planning");
		qualificationList.add("Master of Commerce");
		qualificationList.add("Master of Computational Finance");
		qualificationList.add("Master of Computer Applications");
		qualificationList.add("Master of Computer Science");
		qualificationList.add("Master of Communication");
		qualificationList.add("Master of Counseling");
		qualificationList.add("Master of Criminal Justice");
		qualificationList.add("Master in Creative Technologies");
		qualificationList.add("Master of Design");
		qualificationList.add("Master of Divinity");
		qualificationList.add("Master of Master of Economics");
		qualificationList.add("Master of Education");
		qualificationList.add("Master of Educational Technology");
		qualificationList.add("Master of Engineering");
		qualificationList.add("Master of Engineering Management");
		qualificationList.add("Master of Enterprise");
		qualificationList.add("Master of European Law");
		qualificationList.add("Master of Finance");
		qualificationList.add("Master of Financial Economics");
		qualificationList.add("Master of Financial Engineering");
		qualificationList.add("Master of Financial Mathematics");
		qualificationList.add("Master of Fine Arts");
		qualificationList.add("Master of Health Administration");
		qualificationList.add("Master of Health Science");
		qualificationList.add("Master of Humanities");
		qualificationList.add("Master of Industrial and Labor Relations");
		qualificationList.add("Master of International Affairs");
		qualificationList.add("Master of International Business");
		qualificationList.add("Master of International Economics");
		qualificationList.add("Master of International Public Policy");
		qualificationList.add("Master of International Studies");
		qualificationList.add("Master of Information");
		qualificationList.add("Master of Information Management");
		qualificationList.add("Master of Information Systems");
		qualificationList.add("Master of Information System Management");
		qualificationList.add("Master in Islamic Studies");
		qualificationList.add("Master of IT");
		qualificationList.add("Master of Jurisprudence");
		qualificationList.add("Master of Laws");
		qualificationList.add("Master of Studies in Law");
		qualificationList.add("Master of Landscape Architecture");
		qualificationList.add("Master of Letters");
		qualificationList.add("Master of Liberal Arts");
		qualificationList.add("Master of Library and Information Science");
		qualificationList.add("Master of Management");
		qualificationList.add("Master of Mass Communication and Journalism");
		qualificationList.add("Master of Mathematical Finance");
		qualificationList.add("Master of Mathematics");
		qualificationList.add("Master of Mathematics and Computer Science");
		qualificationList.add("Master of Mathematics and Philosophy");
		qualificationList.add("Master of Medical Science");
		qualificationList.add("Master of Medicine");
		qualificationList.add("Master of Military Art and Science");
		qualificationList.add("Master of Music");
		qualificationList.add("Master of Network and Communications Management");
		qualificationList.add("Master of Occupational Therapy");
		qualificationList.add("Master of Pharmacy");
		qualificationList.add("Master of Philosophy");
		qualificationList.add("Master of Physician Assistant Studies");
		qualificationList.add("Master of Physics");
		qualificationList.add("Master of Political Science");
		qualificationList.add("Master of Professional Studies");
		qualificationList.add("Master of Psychology");
		qualificationList.add("Master of Public Administration");
		qualificationList.add("Master of Public Affairs");
		qualificationList.add("Master of Public Diplomacy");
		qualificationList.add("Master of Public Health");
		qualificationList.add("Master of Public Management");
		qualificationList.add("Master of Public Policy");
		qualificationList.add("Master of Public Relations");
		qualificationList.add("Master of Public Service");
		qualificationList.add("Master of Quantitative Finance");
		qualificationList.add("Master of Rabbinic Studies");
		qualificationList.add("Master of Real Estate Development");
		qualificationList.add("Master of Religious Education");
		qualificationList.add("Master of Research");
		qualificationList.add("Master of Sacred Music");
		qualificationList.add("Master of Sacred Theology");
		qualificationList.add("Master of Science");
		qualificationList.add("Master of Science in Applied Cognition and Neuroscience");
		qualificationList.add("Master of Science in Bioinformatics");
		qualificationList.add("Master of Science in Clinical Epidemiology");
		qualificationList.add("Master of Science in Computing Research");
		qualificationList.add("Master of Science in Cyber Security");
		qualificationList.add("Master of Science in Education");
		qualificationList.add("Master of Science in Engineering");
		qualificationList.add("Master of Science in Development Administration");
		qualificationList.add("Master of Science in Finance");
		qualificationList.add("Master of Science in Governance & Organizational Sciences");
		qualificationList.add("Master of Science in Government Contracts");
		qualificationList.add("Master of Science in Health Informatics");
		qualificationList.add("Master of Science in Human Resource Development");
		qualificationList.add("Master of Science in Information Assurance");
		qualificationList.add("Master of Science in Information Systems");
		qualificationList.add("Master of Science in Information Technology");
		qualificationList.add("Master of Science in Leadership");
		qualificationList.add("Master of Science in Management");
		qualificationList.add("Master of Science in Nursing");
		qualificationList.add("Master of Science in Project Management");
		qualificationList.add("Master of Science in Quality Assurance");
		qualificationList.add("Master of Science in Risk Management");
		qualificationList.add("Master of Science in Supply Chain Management");
		qualificationList.add("Master of Science in Teaching");
		qualificationList.add("Master of Science in Taxation");
		qualificationList.add("Master of Social Science");
		qualificationList.add("Master of Social Work");
		qualificationList.add("Master of Statistics");
		qualificationList.add("Master of Strategic Studies");
		qualificationList.add("Master of Studies");
		qualificationList.add("Master of Surgery");
		qualificationList.add("Master of Theological Studies");
		qualificationList.add("Master of Technology");
		qualificationList.add("Master of Theology");
		qualificationList.add("Master of Urban Planning");
		qualificationList.add("Master of Veterinary Science");
				
		qualificationList.add("Doctor of Business Administration");
		qualificationList.add("Doctor of Canon Law");
		qualificationList.add("Doctor of Chiropractic");
		qualificationList.add("Doctor of Commerce");
		qualificationList.add("Doctor of Dental Surgery");
		qualificationList.add("Doctor of Divinity");
		qualificationList.add("Doctor of Education");
		qualificationList.add("Doctor of Engineering");
		qualificationList.add("Doctor of Health Administration");
		qualificationList.add("Doctor of Health Science");		
		qualificationList.add("Doctor of Juridical Science; Juris Doctor");
		qualificationList.add("Doctor of Law; Legum Doctor");
		qualificationList.add("Doctor of Liberal Studies");
		qualificationList.add("Doctor of Management");
		qualificationList.add("Doctor of Medicine");
		qualificationList.add("Doctor of Ministry");
		qualificationList.add("Doctor of Musical Arts");
		qualificationList.add("Doctor of Naturopathic Medicine");
		qualificationList.add("Doctor of Optometry");
		qualificationList.add("Osteopathic Medicine");		
		qualificationList.add("Doctor of Pharmacy");
		qualificationList.add("Doctor of Philosophy");
		qualificationList.add("Doctor of Public Administration");
		qualificationList.add("Doctor of Science");
		qualificationList.add("Doctor of Theology");
		qualificationList.add("Doctor of Veterinary Medicine");
		
		return qualificationList;
	}

	@Override
	public List<String> fetchExperienceList() {
		List<String> experienceList = new ArrayList<String>(0);
		experienceList.add("Fresher");
		experienceList.add("1 year");
		experienceList.add("2 years");
		experienceList.add("3 years");
		experienceList.add("4 years");
		experienceList.add("5 years");
		experienceList.add("6 years");
		experienceList.add("7 years");
		experienceList.add("8 years");
		experienceList.add("9 years");
		experienceList.add("10 years");
		experienceList.add("11 years");
		experienceList.add("12 years");
		experienceList.add("13 years");
		experienceList.add("14 years");
		experienceList.add("15 years");
		experienceList.add("16 years");
		experienceList.add("17 years");
		experienceList.add("18 years");
		experienceList.add("19 years");
		experienceList.add("20 years");
		experienceList.add("21 years");
		experienceList.add("22 years");
		experienceList.add("23 years");
		experienceList.add("24 years");
		experienceList.add("25 years");
		experienceList.add(">25 years");
		
		return experienceList;
	}

	@Override
	public List<String> fetchEducationList() {
		List<String> educationList = new ArrayList<String>(0);
		educationList.add("Bachelor of Fine Arts (B.F.A.)");
		educationList.add("Bachelor of Social Work (B.S.W.)");
		educationList.add("Bachelor of Engineering (B.Eng.)");
		educationList.add("Bachelor of Science in Public Affairs (B.S.P.A)");
		educationList.add("Bachelor of Science in Nursing (B.S.N.)");
		educationList.add("Bachelor of Philosophy (B.Phil.)");		
		educationList.add("Bachelor of Design (B.Des.)");
		educationList.add("Bachelor of Architecture (B.Arch.)");
		educationList.add("Bachelor of Biomedical Science");
		educationList.add("Bachelor of Business Administration");
		educationList.add("Bachelor of Clinical Science");
		educationList.add("Bachelor of Commerce");
		educationList.add("Bachelor of Computer Applications");
		educationList.add("Bachelor of Computer Information Systems");
		educationList.add("Bachelor of Science in Construction Technology");
		educationList.add("Bachelor of Criminal Justice");
		educationList.add("Bachelor of Divinity");
		educationList.add("Bachelor of Economics");
		educationList.add("Bachelor of Education");
		educationList.add("Bachelor of Information Systems");
		educationList.add("Bachelor of Management");
		educationList.add("Bachelor of Music");
		educationList.add("Bachelor of Pharmacy");
		educationList.add("Bachelor of Philosophy");
		educationList.add("Bachelor of Social Work");
		educationList.add("Bachelor of Technology");
		educationList.add("Bachelor of Accountancy");
		educationList.add("Bachelor of Arts in American Studies");
		educationList.add("Bachelor of Arts in American Indian Studies");
		educationList.add("Bachelor of Arts in Applied Psychology");
		educationList.add("Bachelor of Arts in Biology");
		educationList.add("Bachelor of Arts in Anthropology");
		educationList.add("Bachelor of Arts in Child Advocacy");
		educationList.add("Bachelor of Arts in Clinical Psychology");
		educationList.add("Bachelor of Arts in Forensic Psychology");
		educationList.add("Bachelor of Arts in Organizational Psychology");
		educationList.add("Bachelor of Science in Aerospace Engineering");
		educationList.add("Bachelor of Science in Actuarial");
		educationList.add("Bachelor of Science in Agriculture");
		educationList.add("Bachelor of Science in Architecture");
		educationList.add("Bachelor of Science in Architectural Engineering");
		educationList.add("Bachelor of Science in Biology");
		educationList.add("Bachelor of Science in Biomedical Engineering");
		educationList.add("Bachelor of Science in Business Administration");
		educationList.add("Bachelor of Science in Business and Technology");
		educationList.add("Bachelor of Science in Chemical Engineering");
		educationList.add("Bachelor of Science in Chemistry");
		educationList.add("Bachelor of Science in Civil Engineering");
		educationList.add("Bachelor of Science in Clinical Laboratory Science");
		educationList.add("Bachelor of Science in Cognitive Science");
		educationList.add("Bachelor of Science in Computer Engineering");
		educationList.add("Bachelor of Science in  Computer Science");
		educationList.add("Bachelor of Science in Construction Engineering");
		educationList.add("Bachelor of Science in Construction Management");
		educationList.add("Bachelor of Science in Criminal Justice");
		educationList.add("Bachelor of Science in Criminology");
		educationList.add("Bachelor of Science in Diagnostic Radiography");
		educationList.add("Bachelor of Science in Education");
		educationList.add("Bachelor of Science in Electrical Engineering");
		educationList.add("Bachelor of Science in Engineering Physics");
		educationList.add("Bachelor of Science in Engineering Science");
		educationList.add("Bachelor of Science in Engineering Technology");
		educationList.add("Bachelor of Science in English Literature");
		educationList.add("Bachelor of Science in Environmental Engineering");		
		educationList.add("Bachelor of Science in Environmental Science");
		educationList.add("Bachelor of Science in Environmental Studies");
		educationList.add("Bachelor of Science in Food Science");
		educationList.add("Bachelor of Science in Foreign Service");
		educationList.add("Bachelor of Science in Forensic Science");
		educationList.add("Bachelor of Science in Forestry");
		educationList.add("Bachelor of Science in History");
		educationList.add("Bachelor of Science in Hospitality Management");
		educationList.add("Bachelor of Science in Human Resources Management");
		educationList.add("Bachelor of Science in Industrial Engineering");
		educationList.add("Bachelor of Science in Information Technology");
		educationList.add("Bachelor of Science in Information Systems");
		educationList.add("Bachelor of Science in Integrated Science");
		educationList.add("Bachelor of Science in International Relations");
		educationList.add("Bachelor of Science in Journalism");
		educationList.add("Bachelor of Science in Legal Management");
		educationList.add("Bachelor of Science in Management");
		educationList.add("Bachelor of Science in Manufacturing Engineering");
		educationList.add("Bachelor of Science in Marketing");
		educationList.add("Bachelor of Science in Mathematics");
		educationList.add("Bachelor of Science in Mechanical Engineering");
		educationList.add("Bachelor of Science in Medical Technology");
		educationList.add("Bachelor of Science in Meteorology");
		educationList.add("Bachelor of Science in Microbiology");
		educationList.add("Bachelor of Science in Mining Engineering");
		educationList.add("Bachelor of Science in Molecular Biology");
		educationList.add("Bachelor of Science in Neuroscience");
		educationList.add("Bachelor of Science in Nursing");		
		educationList.add("Bachelor of Science in Nutrition science");
		educationList.add("Bachelor of Science in Software Engineering");
		educationList.add("Bachelor of Science in Petroleum Engineering");
		educationList.add("Bachelor of Science in Podiatry");
		educationList.add("Bachelor of Science in Pharmacology");
		educationList.add("Bachelor of Science in Pharmacy");
		educationList.add("Bachelor of Science in Physical Therapy");
		educationList.add("Bachelor of Science in Physics");
		educationList.add("Bachelor of Science in Plant Science");
		educationList.add("Bachelor of Science in Politics");
		educationList.add("Bachelor of Science in Psychology");
		educationList.add("Bachelor of Science in Public Safety");
		educationList.add("Bachelor of Science in Quantity Surveying Engineering");
		educationList.add("Bachelor of Science in Radiologic Technology");
		educationList.add("Bachelor of Science in Real-Time Interactive Simulation");
		educationList.add("Bachelor of Science in Religion");
		educationList.add("Bachelor of Science in Respiratory Therapy");
		educationList.add("Bachelor of Science in Risk Management and Insurance");
		educationList.add("Bachelor of Science in Sports Management");
		educationList.add("Bachelor of Science in Science Education");
		educationList.add("Bachelor of Science in Sports Management");
		educationList.add("Bachelor of Science in Systems Engineering");
		educationList.add("Bachelor of Science in Veterinary Technology");
		
		educationList.add("Bachelor of Music in Jazz Studies");
		educationList.add("Bachelor of Music in Composition");
		educationList.add("Bachelor of Music in Performance");
		educationList.add("Bachelor of Music in Theory");
		educationList.add("Bachelor of Music in Music Education");	
		
		educationList.add("Master of Accountancy");
		educationList.add("Master of Advanced Study");
		educationList.add("Master of Applied Finance");
		educationList.add("Master of Applied Mathematical Sciences");
		educationList.add("Master of Applied Science");
		educationList.add("Master of Architecture");
		educationList.add("Master of Arts");
		educationList.add("Master of Arts in Liberal Studies");
		educationList.add("Master of Arts in Strategic Communication Management");
		educationList.add("Master of Arts in Teaching");
		educationList.add("Master of Bioinformatics");
		educationList.add("Master of Business Administration");
		educationList.add("Master of Business Administration Management of Technology");
		educationList.add("Master of Business");
		educationList.add("Master of Business Economics");
		educationList.add("Master of Business Engineering");
		educationList.add("Master of Business Informatics");
		educationList.add("Master of Chemistry");
		educationList.add("Master of City Planning");
		educationList.add("Master of Commerce");
		educationList.add("Master of Computational Finance");
		educationList.add("Master of Computer Applications");
		educationList.add("Master of Computer Science");
		educationList.add("Master of Communication");
		educationList.add("Master of Counseling");
		educationList.add("Master of Criminal Justice");
		educationList.add("Master in Creative Technologies");
		educationList.add("Master of Design");
		educationList.add("Master of Divinity");
		educationList.add("Master of Master of Economics");
		educationList.add("Master of Education");
		educationList.add("Master of Educational Technology");
		educationList.add("Master of Engineering");
		educationList.add("Master of Engineering Management");
		educationList.add("Master of Enterprise");
		educationList.add("Master of European Law");
		educationList.add("Master of Finance");
		educationList.add("Master of Financial Economics");
		educationList.add("Master of Financial Engineering");
		educationList.add("Master of Financial Mathematics");
		educationList.add("Master of Fine Arts");
		educationList.add("Master of Health Administration");
		educationList.add("Master of Health Science");
		educationList.add("Master of Humanities");
		educationList.add("Master of Industrial and Labor Relations");
		educationList.add("Master of International Affairs");
		educationList.add("Master of International Business");
		educationList.add("Master of International Economics");
		educationList.add("Master of International Public Policy");
		educationList.add("Master of International Studies");
		educationList.add("Master of Information");
		educationList.add("Master of Information Management");
		educationList.add("Master of Information Systems");
		educationList.add("Master of Information System Management");
		educationList.add("Master in Islamic Studies");
		educationList.add("Master of IT");
		educationList.add("Master of Jurisprudence");
		educationList.add("Master of Laws");
		educationList.add("Master of Studies in Law");
		educationList.add("Master of Landscape Architecture");
		educationList.add("Master of Letters");
		educationList.add("Master of Liberal Arts");
		educationList.add("Master of Library and Information Science");
		educationList.add("Master of Management");
		educationList.add("Master of Mass Communication and Journalism");
		educationList.add("Master of Mathematical Finance");
		educationList.add("Master of Mathematics");
		educationList.add("Master of Mathematics and Computer Science");
		educationList.add("Master of Mathematics and Philosophy");
		educationList.add("Master of Medical Science");
		educationList.add("Master of Medicine");
		educationList.add("Master of Military Art and Science");
		educationList.add("Master of Music");
		educationList.add("Master of Network and Communications Management");
		educationList.add("Master of Occupational Therapy");
		educationList.add("Master of Pharmacy");
		educationList.add("Master of Philosophy");
		educationList.add("Master of Physician Assistant Studies");
		educationList.add("Master of Physics");
		educationList.add("Master of Political Science");
		educationList.add("Master of Professional Studies");
		educationList.add("Master of Psychology");
		educationList.add("Master of Public Administration");
		educationList.add("Master of Public Affairs");
		educationList.add("Master of Public Diplomacy");
		educationList.add("Master of Public Health");
		educationList.add("Master of Public Management");
		educationList.add("Master of Public Policy");
		educationList.add("Master of Public Relations");
		educationList.add("Master of Public Service");
		educationList.add("Master of Quantitative Finance");
		educationList.add("Master of Rabbinic Studies");
		educationList.add("Master of Real Estate Development");
		educationList.add("Master of Religious Education");
		educationList.add("Master of Research");
		educationList.add("Master of Sacred Music");
		educationList.add("Master of Sacred Theology");
		educationList.add("Master of Science");
		educationList.add("Master of Science in Applied Cognition and Neuroscience");
		educationList.add("Master of Science in Bioinformatics");
		educationList.add("Master of Science in Clinical Epidemiology");
		educationList.add("Master of Science in Computing Research");
		educationList.add("Master of Science in Cyber Security");
		educationList.add("Master of Science in Education");
		educationList.add("Master of Science in Engineering");
		educationList.add("Master of Science in Development Administration");
		educationList.add("Master of Science in Finance");
		educationList.add("Master of Science in Governance & Organizational Sciences");
		educationList.add("Master of Science in Government Contracts");
		educationList.add("Master of Science in Health Informatics");
		educationList.add("Master of Science in Human Resource Development");
		educationList.add("Master of Science in Information Assurance");
		educationList.add("Master of Science in Information Systems");
		educationList.add("Master of Science in Information Technology");
		educationList.add("Master of Science in Leadership");
		educationList.add("Master of Science in Management");
		educationList.add("Master of Science in Nursing");
		educationList.add("Master of Science in Project Management");
		educationList.add("Master of Science in Quality Assurance");
		educationList.add("Master of Science in Risk Management");
		educationList.add("Master of Science in Supply Chain Management");
		educationList.add("Master of Science in Teaching");
		educationList.add("Master of Science in Taxation");
		educationList.add("Master of Social Science");
		educationList.add("Master of Social Work");
		educationList.add("Master of Statistics");
		educationList.add("Master of Strategic Studies");
		educationList.add("Master of Studies");
		educationList.add("Master of Surgery");
		educationList.add("Master of Theological Studies");
		educationList.add("Master of Technology");
		educationList.add("Master of Theology");
		educationList.add("Master of Urban Planning");
		educationList.add("Master of Veterinary Science");
				
		educationList.add("Doctor of Business Administration");
		educationList.add("Doctor of Canon Law");
		educationList.add("Doctor of Chiropractic");
		educationList.add("Doctor of Commerce");
		educationList.add("Doctor of Dental Surgery");
		educationList.add("Doctor of Divinity");
		educationList.add("Doctor of Education");
		educationList.add("Doctor of Engineering");
		educationList.add("Doctor of Health Administration");
		educationList.add("Doctor of Health Science");		
		educationList.add("Doctor of Juridical Science; Juris Doctor");
		educationList.add("Doctor of Law; Legum Doctor");
		educationList.add("Doctor of Liberal Studies");
		educationList.add("Doctor of Management");
		educationList.add("Doctor of Medicine");
		educationList.add("Doctor of Ministry");
		educationList.add("Doctor of Musical Arts");
		educationList.add("Doctor of Naturopathic Medicine");
		educationList.add("Doctor of Optometry");
		educationList.add("Osteopathic Medicine");		
		educationList.add("Doctor of Pharmacy");
		educationList.add("Doctor of Philosophy");
		educationList.add("Doctor of Public Administration");
		educationList.add("Doctor of Science");
		educationList.add("Doctor of Theology");
		educationList.add("Doctor of Veterinary Medicine");
		
		return educationList;
	}

}
